[platformio]
src_dir = src

[env:m5stamp-s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 1500000

; ESP32-S3 Flash & PSRAM Optimierungen für 8MB Flash & OPI PSRAM
board_build.mcu = esp32s3
board_build.f_cpu = 240000000L
board_build.f_flash = 80000000L
board_build.flash_mode = qio
board_build.flash_size = 8MB
board_build.partitions = default_8MB.csv

build_flags =
    -D BOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue

lib_deps =
    m5stack/M5Unified
