[platformio]
src_dir = src

[env:m5stick-c-plus2]
platform = espressif32
board = m5stick-c
framework = arduino
monitor_speed = 115200
upload_speed = 1500000

lib_ldf_mode = deep+

lib_deps = 
	m5stack/M5Unified
	m5stack/M5GFX
	bogde/HX711